### ISSUE TITLE
Yay!

### ISSUE THREAD

**Issue by loctauxphilippe** [Nicell/nicell.github.io#1]
You're doing your website! Finally! Will you do it with Polymer?

**Comment by Nicell** [comment]
Yes, finally. I'm not sure. I don't know how to use Polymer yet. I'm using this website to help me improve my understanding of HTML CSS and JavaScript.

**Comment by loctauxphilippe** [comment]
@Nicell Great! I can help you if you want! :-)

**Comment by loctauxphilippe** [comment]
we can close this
